---
- name: ups install packages
  apt:
    name: "{{ ups__default_packages }}"
    update_cache: yes
    state: present
  when: ups__install

- name: Setup config file apcupsd.conf
  template:
    src: apcupsd.conf
    dest: /etc/apcupsd/apcupsd.conf
  when:
    - ups__configure

- include_tasks: setup_scripts.yml
  loop: "{{ ups__scriptlist }}"
  when:
    - ups__configure

