#!/bin/sh
#
# This shell script if placed in /etc/apcupsd
# will be called by /etc/apcupsd/apccontrol when apcupsd
# want to start a shutdown
#

HOSTNAME=`hostname`
MSG="$HOSTNAME UPS $1 shutdown will be initiated."
#
TIME_REMAINING=$(/sbin/apcaccess -u -p TIMELEFT|sed 's/\..*//')
CHARGE_REMAINING=$(/sbin/apcaccess -u -p BCHARGE|sed 's/\..*//')
if [ "${TIME_REMAINING}" -gt "5" ]
then
    MSG="$HOSTNAME UPS $1 battery reported wrongly failing"
  (
   echo "$MSG"
   echo " "
   echo "Time remaining: >$TIME_REMAINING<"
   echo " "
   /sbin/apcaccess status
  ) | $APCUPSD_MAIL -s "$MSG" $SYSADMIN
{% if ups__use_signal|default(False) %}
    signal-cli -a "{{ ups__signal_from }}" send -m "$MSG" "{{ ups__signal_to }}"
{% endif %}
    exit 99
fi

if [ "${CHARGE_REMAINING}" -gt "8" ]
then
    MSG="$HOSTNAME UPS $1 battery reported wrongly failing"
  (
   echo "$MSG"
   echo " "
   echo "Charge remaining: >$CHARGE_REMAINING<"
   echo " "
   /sbin/apcaccess status
  ) | $APCUPSD_MAIL -s "$MSG" $SYSADMIN
{% if ups__use_signal|default(False) %}
    signal-cli -a "{{ ups__signal_from }}" send -m "$MSG" "{{ ups__signal_to }}"
{% endif %}
    exit 99
fi
(
 echo "$MSG"
 echo " "
 echo "Full status:"
 echo " "
 /sbin/apcaccess status
) | $APCUPSD_MAIL -s "$MSG" $SYSADMIN
{% if ups__use_signal|default(False) %}
signal-cli -a "{{ ups__signal_from }}" send -m "$MSG" "{{ ups__signal_to }}"
{% endif %}
exit 0
